### ISSUE TITLE
Unable to solve low severity vulnerability when using rocketchat boilerplate code and couldn't connect to my rocket chat server

### ISSUE THREAD

**Issue by RADHAKRISHNAMOHAN** [RocketChat/hubot-rocketchat-boilerplate#7]
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
body-parser deprecated undefined extended: provide extended option ..\node_modules\hubot\src\robot.js:446:21
[Wed Feb 06 2019 11:05:17 GMT+0530 (India Standard Time)] INFO [startup] Rocket.Chat adapter in use
[Wed Feb 06 2019 11:05:17 GMT+0530 (India Standard Time)] INFO [startup] Respond to name: Hubot
[Wed Feb 06 2019 11:05:17 GMT+0530 (India Standard Time)] INFO [startup] Respond to alias: chat.bot
[Wed Feb 06 2019 11:05:17 GMT+0530 (India Standard Time)] INFO [connect] Connecting { username: '......',
  password: '.......',
  ldap: false,
  host: 'myhost',
  useSsl: true,
  timeout: 20000,
  rooms: [ 'GENERAL' ],
  allPublic: false,
  dm: false,
  livechat: false,
  edited: false,
  integrationId: 'js.SDK',
  roomCacheMaxSize: 10,
  roomCacheMaxAge: 300000,
  dmCacheMaxSize: 10,
  dmCacheMaxAge: 100000 }
[Wed Feb 06 2019 11:05:37 GMT+0530 (India Standard Time)] INFO [connect] Timeout (20000)
[Wed Feb 06 2019 11:05:37 GMT+0530 (India Standard Time)] ERROR Unable to connect: {}
[Wed Feb 06 2019 11:05:37 GMT+0530 (India Standard Time)] ERROR undefined
[Wed Feb 06 2019 11:05:37 GMT+0530 (India Standard Time)] ERROR Unable to login: {}
[Wed Feb 06 2019 11:05:37 GMT+0530 (India Standard Time)] ERROR undefined
[Wed Feb 06 2019 11:05:37 GMT+0530 (India Standard Time)] ERROR Unable to subscribe {}
(node:1248) UnhandledPromiseRejectionWarning: Error: Asteroid connection timeout
    at Timeout._onTimeout (C:\Users\username\hubot-rocketchat-boilerplate\node_modules\@rocket.chat\sdk\dist\lib\driver.js:94:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

(node:1248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SpongeGirl** [comment]
Right now, i have the same problem, have you fixed it? If so, i hope you can tell me the solution, thanks a lot.

**Comment by RADHAKRISHNAMOHAN** [comment]
No, I will look into it later and comment here. Thanks
